---
title: "Modelagem Conjunta de Dados Longitudinais e de Sobrevivência"
author: 
- Ítalo Ferreira Fernandes
- Ruy Azevedo Cota Vasconcelos
date: "Universidade Federal de Minas Gerais (UFMG)"
output:
  ioslides_presentation:
    widescreen: true
    smaller: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introdução

## Dado de tempo até o evento

O tempo até o evento é o dado primordial da análise de sobrevivência. 

Na análise de sobrevivência precisamos saber se o evento acorreu ou foi censurado e qual foi o tempo acompanhamos até esse evento. Além de conseguirmos comparar os pacientes com tratamento dos sem tratamento.

Essa modelagem consegue retornar as taxas de riscos e a probabilidade de sobrevivência.

## Dado longitudinal

Um dado pode ser considerado longitudinal quando coletamos ele em diferentes pontos no tempo. 

Por tanto, os dados longitudinais podem ser ótimos preditores para o tempo até o evento em um ensaio clínico.

Neste caso, não é mais importante o tempo até o evento mas qual o valor das medidas em certo tempo.

E em situações na qual o tempo até o evento é importante, assim como as medidas em cada tempo?

## Modelo conjunto

Modelos clássicos como o modelo linear misto para dados longitudinais e o modelo de riscos proporcionais de Cox não levam em conta a dependência entre essas dois tipos de dados. 
Então, a modelagem conjunta foi proposta com objetivo de levar em consideração essa dependência.

Essa modelagem produz estimativas mais eficientes para o efeito da tratamento no tempo até o evento e para o efeito da tratamento dos marcadores longitudinais. Além de reduzir o viés da estimativa do efeito geral do tratamento.
A melhora nas estimativas implica em um aumento de poder e uma redução da amostra para o design dos ensaios clínicos.

Essas propriedades foram demonstradas no *Chen et al*, além de serem demonstradas aqui também.

# Estrutura do modelo conjunto

## Parte longitudinal

O componente longitudinal consiste no modelo misto linear, que pode ser escrito como:

* $Y_{ij} = X_{ij} +\epsilon_{ij}$;

  * $Y_{ij}$ é a resposta observada do i-ésimo indivíduo no tempo j-ésimo;
  
  * $\epsilon_{ij}$ é o erro aleatório que assumimos que vem de uma distribuição normal;

##

* $X_{ij} = \theta_{0i} + \theta_{1i} t_{ij} +\gamma Z_i$;

  * $X_{ij}$ é conhecida como função trajetória do modelo;
  
  * $t_{ij}$ é o tempo?;

##

  * $Z_i$ é o indicador de tratamento do i-ésimo indivíduo;
  
  * $\theta_{0i}$ e $\theta_{1i}$ assumimos serem aleatórios com distribuição normal multivariada.
  
  * $\gamma$ indica o efeito do tratamento no processo longitudinal. Assumimos distribuição normal com média 0 e variância desconhecida.

## Parte de sobrevivência

Enquanto o componente de sobrevivência consiste em um modelo paramêtrico, como por exemplo, o modelo exponencial.

Portanto, escrevemos a função de risco do modelo de sobrevivência como:

* $h(t) = h_o(t)exp(\beta X_{ij}+\alpha Z_i)$;

  * $h(t)$ é a probabilidade do evento ocorrer no tempo t;
  
  * $h_o(t)$ é ?
  
  * $\alpha$ é o efeito do tratamento no tempo até o avento;
  
  * $\beta$ é o efeito do processo longitudinal na análise de sobrevivência.

## 

Temos, então, três tipos diferentes efeitos: \(\alpha\), \(\beta\) e \(\gamma\), sendo que podemos juntar os três: $\beta\gamma + \alpha$, para obter o efeito geral do tratamento. Nosso principal objetivo infeencial é estimar esse parâmetros, porque ele nos da informações importantes para a análise.

## Interpretações dos efeitos
O $\beta = 0$ significa que a resposta longitudinal não tem associação com o tempo até o evento. Quer dizer que os dados longitudinais não alteram o risco, portanto, não precisa-se de modelo conjunto neste caso. 

O $\beta = 0.5$ significa que o risco aumenta em 0.5 para cada unidade aumentada na trajetória que qualquer grupo de tratamento.

Se $\alpha$ for negativo, o risco de quem recebe tratamento é menor de quem não recebe, portanto, há indícios de que o tratamento seja eficiente.

Se $\gamma = 0$ significa que que o tratamento não interfere na mudança dos dados longitudinais.

# Exemplos 
## Exemplos| 
 - Quality-of-Life (QOL)
 - E1193
 - Simulação

## QOL

* Caracterização da associação entre tempo até o evento e QOL atravéz modelamento conjunto.

* Entender a troca entre QOL e sobrevivência.

  * Uma certo tratamento pode prolongar a sobrevivência, mas a qualidade de vida nesse período prolongado pode ser ruim.

## Análise do modelo conjunto de _E1193_

* Experimento em grupo E1193 - Eastern Cooperative Oncology

* Examinar a associação entre QOL e tempo de sobrevivência médio para pacientes no estudo.

* Estudo clínico de fase III de doxorubicin, paclitaxel e uma combinação dos dois como tratamento quemoterápico de ponta contra câncer de mama metastático.

## _E1193_

* Pacientes que recebiam um dos dois tratamentos "simples" - doxorubicin ou paclitaxel apenas - trocaram para o outro agente durante o estudo.

* QOL foi acessada por uma escala de avaliação de terapia de câncer de mama. (Brady et al)

* Essa avaliação inclui cinco subescalas gerais - Física, social, relacionamento com o médico, emocional e funcional.

* Assim com subescalas específicas para câncer de mama.

## _E1193_

* Pontuação máxima de 148 pontos;

  * Quanto maior a pontuação, melhor a qualidade de vida do paciente.
  
* Análise do tempo de sobrevivência após entrar na fase de cross-over (progressão da doença) e associação entre tratamento e QOL;

  * QOL medida em 2 pontos durante essa fase.
  
## _E1193_

* 252 pacientes tiveram pelo menos uma medição de QOL realizada.

* 124 pacientes: paclitaxel \(\rightarrow\) doxorubicin;

  * Tempo de vida mediano: 13 meses;
  
  * 2 censuras.

* 128 pacientes: doxorubicin \(\rightarrow\) paclitaxel;

  * Tempo de vida mediano: 14.9 meses;
  
  * 6 censuras.
  
  
## _E1193_

* Contudo, apenas 65% dos pacientes tiveram 2 medições de QOL realizadas;

  * Esses dados faltantes podem introduzir viés na estimativa do efeito de QOL e do tratamento;
  
* Dados discrepantes não foram excluídos;

* Essas escolhas foram feitas devido a confiança na habilidade do modelo conjunto em reduzir o viés proveniente de dados incompletos ou com erro.

## _E1193_

* Função de trajetória

* 
 
## Simulação

## Conclusão

## Referência
teste de ortografia fe corrigi filhou 
